### ISSUE TITLE
"work in progress" Flow types

### ISSUE THREAD

**Issue by Gerrit0** [shobhitg/road-to-typescript#1]
The [`$Supertype<T>`](https://flow.org/en/docs/types/utilities/#toc-supertype) and [`$Subtype<T>`](https://flow.org/en/docs/types/utilities/#toc-subtype) Flow types aren't yet documented. They apparently already exist ([blog post covering them](https://medium.com/netscape/secret-flow-types-86b2ebb30951#8e62)), but without official documentation, I'm wary about including them in a comparison since it would be very easy to present an incorrect solution.

Should these entries be removed until they have been documented by the Flow team?

**Comment by shobhitg** [comment]
Right I didn't realize that `$Supertype<T>` and `$Subtype<T>` are WIP.
I will remove them for now.
