### ISSUE TITLE
Assert missing reducer - overly complex?

### ISSUE THREAD

**Issue by Gerrit0** [shobhitg/road-to-typescript#3]
Is there a reason that the assert missing reducer example needs the `assertNever` function? If the return type of `areaReducer` is specified, we can get rid of it. [Playground](https://agentcooper.github.io/typescript-play/#code/JYOwLgpgTgZghgYwgAgMoEcCucooN4BQyyA1qACYBcyARAM5Y4Q0DcRydwAXhNSJgFsARtDYBfAqEixEKAEoQEYOCADmAG3zsyIKrVxKVG5m2IB3YOTAALPoJFRTyaxGCrrYO8NEEJU6PBIyADCwFAImsiExDp6NAhhESbsUHDkwJh0Xg7iBARgAJ4ADiio1nAlyAC8aIy4yAA+yAqGapFNoeGabAQwmCBKwAD2IMhMcArkmEhQABRZaOUlAJTZ0FHsdBZgCNbI8wB0scsbxMQIcHQo9HXMlOxnyLhgmFCjdAecPMgAVByf3AgTnOl2uBmUbTuDzOz1e7wOLjcHl+-wsVmswOQAHoscgLldaAkulDHjjHk8IC83sgALJwGwHAAKAEkUR9UulMr8-gAmJwSCRAA)

```ts
interface Square {
  kind: "square";
  size: number;
}
interface Rectangle {
  kind: "rectangle";
  width: number;
  height: number;
}
interface Circle {
  kind: "circle";
  radius: number;
}

type Shape = Square | Rectangle | Circle;

function areaReducer(s: Shape): number {
  switch (s.kind) {
    case "square":
      return s.size * s.size;
    case "rectangle":
      return s.height * s.width;
    // case "circle":
    //     return Math.PI * s.radius ** 2;
  }
}
```

**Comment by shobhitg** [comment]
Very interesting, didn't realize that if not all cases are returning something than return would be unionized with `void`.

I think its still interesting for folks to see this complex assert version.

_Here is the reasoning:_
In large teams you can't control if someone adds a default case to a switch statement. And as we know in redux world, folks are very used to add these two lines in a switch case:
```
    default:
      return state;
```
And as soon as this default is added, the error would disappear.
Its guaranteed to happen to any reducer code.

Instead if one of the experienced team members preemptively adds:
```
    default:
      assertNever(s);
```
then the assert/error would likely stay.
